
create table if not exists products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  name text,
  char1 text,
  char2 text,
  category text,
  stock integer default 0,
  wholesale integer default 0,
  retail integer default 0,
  hidden boolean default false
);

create table if not exists orders (
  id bigint generated by default as identity primary key,
  created_at text,
  customer text,
  reorder integer default 0,
  memo text,
  sale_price integer default 0,
  fee_rate numeric default 0,
  fee_amount integer default 0,
  wholesale_sum integer default 0,
  retail_sum integer default 0,
  net_amount integer default 0,
  profit integer default 0,
  status text default '주문접수',
  cancel_reason text default ''
);

create table if not exists order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references orders(id) on delete cascade,
  product_id bigint,
  name text,
  qty integer default 1,
  wholesale integer default 0,
  retail integer default 0
);

create table if not exists materials (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  name text,
  amount integer default 0
);

create table if not exists settings (
  k text primary key,
  v text
);

alter table products enable row level security;
alter table orders enable row level security;
alter table order_items enable row level security;
alter table materials enable row level security;
alter table settings enable row level security;

drop policy if exists "allow all products" on products;
drop policy if exists "allow all orders" on orders;
drop policy if exists "allow all order_items" on order_items;
drop policy if exists "allow all materials" on materials;
drop policy if exists "allow all settings" on settings;

create policy "allow all products" on products for all to anon using (true) with check (true);
create policy "allow all orders" on orders for all to anon using (true) with check (true);
create policy "allow all order_items" on order_items for all to anon using (true) with check (true);
create policy "allow all materials" on materials for all to anon using (true) with check (true);
create policy "allow all settings" on settings for all to anon using (true) with check (true);


-- v14 safety tables
create table if not exists inventory_backups (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  reason text,
  data text
);

create table if not exists audit_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  action text,
  detail text
);

alter table inventory_backups enable row level security;
alter table audit_logs enable row level security;

drop policy if exists "allow all inventory_backups" on inventory_backups;
drop policy if exists "allow all audit_logs" on audit_logs;

create policy "allow all inventory_backups" on inventory_backups for all to anon using (true) with check (true);
create policy "allow all audit_logs" on audit_logs for all to anon using (true) with check (true);


-- v18 login security policies
-- 기존 anon 전체허용 정책을 제거하고, 로그인한 사용자(authenticated)만 접근 가능하게 변경합니다.
-- 기존 데이터는 삭제되지 않습니다.

alter table products enable row level security;
alter table orders enable row level security;
alter table order_items enable row level security;
alter table materials enable row level security;
alter table settings enable row level security;
alter table inventory_backups enable row level security;
alter table audit_logs enable row level security;

drop policy if exists "allow all products" on products;
drop policy if exists "allow all orders" on orders;
drop policy if exists "allow all order_items" on order_items;
drop policy if exists "allow all materials" on materials;
drop policy if exists "allow all settings" on settings;
drop policy if exists "allow all inventory_backups" on inventory_backups;
drop policy if exists "allow all audit_logs" on audit_logs;

drop policy if exists "authenticated products" on products;
drop policy if exists "authenticated orders" on orders;
drop policy if exists "authenticated order_items" on order_items;
drop policy if exists "authenticated materials" on materials;
drop policy if exists "authenticated settings" on settings;
drop policy if exists "authenticated inventory_backups" on inventory_backups;
drop policy if exists "authenticated audit_logs" on audit_logs;

create policy "authenticated products" on products for all to authenticated using (true) with check (true);
create policy "authenticated orders" on orders for all to authenticated using (true) with check (true);
create policy "authenticated order_items" on order_items for all to authenticated using (true) with check (true);
create policy "authenticated materials" on materials for all to authenticated using (true) with check (true);
create policy "authenticated settings" on settings for all to authenticated using (true) with check (true);
create policy "authenticated inventory_backups" on inventory_backups for all to authenticated using (true) with check (true);
create policy "authenticated audit_logs" on audit_logs for all to authenticated using (true) with check (true);


-- v23 cancel/trash fields
alter table orders add column if not exists canceled_at text;
alter table orders add column if not exists deleted_at text;
alter table orders add column if not exists cancel_detail text;

-- v92 live broadcast order management
create table if not exists live_sessions (
  id text primary key,
  created_at text,
  title text,
  date text,
  keep_days text default '7',
  shipping_fee text default '4000',
  card_fee_rate text default '3',
  bank_name text,
  account_number text,
  account_holder text,
  notice text,
  products jsonb default '[]'::jsonb
);

create table if not exists live_members (
  id text primary key,
  updated_at text,
  name text,
  phone text,
  address text,
  points text default '0',
  memo text,
  keep_start text,
  keep_days text default '7'
);

create table if not exists live_orders (
  id text primary key,
  session_id text,
  live_title text,
  live_date text,
  created_at text,
  updated_at text,
  buyer text,
  phone text,
  address text,
  payment_method text default '계좌이체',
  status text default '미입금',
  tracking_no text,
  memo text,
  shipping_apply boolean default true,
  card_apply boolean default false,
  items jsonb default '[]'::jsonb,
  subtotal integer default 0,
  pay_subtotal integer default 0,
  shipping integer default 0,
  card_fee integer default 0,
  total integer default 0,
  locked boolean default false,
  canceled_at text,
  cancel_reason text
);

alter table live_sessions enable row level security;
alter table live_members enable row level security;
alter table live_orders enable row level security;

drop policy if exists "authenticated live_sessions" on live_sessions;
drop policy if exists "authenticated live_members" on live_members;
drop policy if exists "authenticated live_orders" on live_orders;

create policy "authenticated live_sessions" on live_sessions for all to authenticated using (true) with check (true);
create policy "authenticated live_members" on live_members for all to authenticated using (true) with check (true);
create policy "authenticated live_orders" on live_orders for all to authenticated using (true) with check (true);

-- v94 live page workflow refinements
-- 기존 라방 테이블을 유지하면서 주문/회원/택배/합배송에 필요한 컬럼을 추가합니다.
alter table live_members add column if not exists postal_code text;
alter table live_members add column if not exists base_address text;
alter table live_members add column if not exists detail_address text;

alter table live_orders add column if not exists postal_code text;
alter table live_orders add column if not exists base_address text;
alter table live_orders add column if not exists detail_address text;
alter table live_orders add column if not exists box_weight text default '2';
alter table live_orders add column if not exists box_volume text default '60';
alter table live_orders add column if not exists household text default '생활용품';
alter table live_orders add column if not exists delivery_message text;
alter table live_orders add column if not exists member_key text;
alter table live_orders add column if not exists bundle_id text;
alter table live_orders add column if not exists deducted boolean default false;
alter table live_orders add column if not exists paid_at text;

-- v100 member points + invoice point deduction
alter table live_members add column if not exists used_points integer default 0;
alter table live_orders add column if not exists used_points integer default 0;
